name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PDK_ROOT: "/home/runner/work/pdk"
  OPENLANE_ROOT: "/home/runner/work/openlane"
  PDK: "sky130A"

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: setup
        run: |
          make setup
          make precheck

      - name: harden
        run: |
          make user_module
          make user_project_wrapper

      - name: precheck
        run: |
          make run-precheck
