name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  PDK_ROOT: "/home/runner/work/pdk"
  OPENLANE_ROOT: "/home/runner/work/openlane"
  PDK: "sky130A"

jobs:
  gds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup
        run: |
          make setup

      - name: harden
        run: |
          make fetch
          make user_module
          make user_project_wrapper

      - name: cache gds
        uses: actions/cache@v3
        with:
          path: gds
          key: ${{ runner.os }}-gds-${{ github.run_id }}

  precheck:
    needs:
    - gds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup
        run: |
          make precheck

      - name: restore runs cache
        uses: actions/cache@v3
        with:
          path: gds
          key: ${{ runner.os }}-gds-${{ github.run_id }}

      - name: check
        run: |
          make run-precheck
